export const programmingLanguages = [
  { value: "amazonwebservices", label: "AWS" },
  { value: "android", label: "Android" },
  { value: "angularjs", label: "Angular JS" },
  { value: "apache", label: "Apache" },
  { value: "babel", label: "Babel" },
  { value: "backbonejs", label: "Backbone JS" },
  { value: "bootstrap", label: "Bootstrap" },
  { value: "c", label: "C" },
  { value: "cplusplus", label: "C++" },
  { value: "csharp", label: "C#" },
  { value: "css3", label: "CSS" },
  { value: "django", label: "Django" },
  { value: "docker", label: "Docker" },
  { value: "git", label: "Git" },
  { value: "github", label: "Github" },
  { value: "gradle", label: "Gradle" },
  { value: "heroku", label: "Heroku" },
  { value: "java", label: "Java" },
  { value: "javascript", label: "JS" },
  { value: "jquery", label: "Jquery" },
  { value: "laravel", label: "Laravel" },
  { value: "linux", label: "Linux" },
  { value: "mongodb", label: "MongoDB" },
  { value: "mysql", label: "MySQL" },
  { value: "nodejs", label: "Node JS" },
  { value: "oracle", label: "Oracle" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "python", label: "Python" },
  { value: "rails", label: "Rails" },
  { value: "react", label: "React" },
  { value: "ruby", label: "Ruby" },
  { value: "sourcetree", label: "SourceTree" },
  { value: "swift", label: "Swift" },
  { value: "tomcat", label: "Tomcat" },
  { value: "typescript", label: "TypeScript" },
  { value: "ubuntu", label: "Ubuntu" },
  { value: "vim", label: "Vim" },
  { value: "vuejs", label: "Vue JS" },
  { value: "webpack", label: "Webpack" }
];

export const languageMapper = {
  amazonwebservices: "original-wordmark",
  android: "original-wordmark",
  angularjs: "original",
  apache: "original-wordmark",
  babel: "plain",
  backbonejs: "original-wordmark",
  bootstrap: "plain-wordmark",
  c: "line",
  cplusplus: "plain",
  csharp: "plain",
  css3: "original-wordmark",
  django: "plain",
  docker: "original-wordmark",
  git: "original-wordmark",
  github: "original",
  go: "plain",
  gradle: "plain",
  heroku: "plain-wordmark",
  html5: "original-wordmark",
  java: "original-wordmark",
  javascript: "original",
  jquery: "original-wordmark",
  laravel: "plain-wordmark",
  linux: "original",
  mongodb: "original-wordmark",
  mysql: "original-wordmark",
  nodejs: "original-wordmark",
  oracle: "original",
  php: "plain",
  postgresql: "original-wordmark",
  python: "original",
  rails: "original-wordmark",
  react: "original-wordmark",
  ruby: "original-wordmark",
  sourcetree: "original-wordmark",
  swift: "original",
  tomcat: "original-wordmark",
  typescript: "original",
  ubuntu: "plain-wordmark",
  vim: "original",
  vuejs: "original",
  webpack: "original"
};

export const colourOptions = [
  { value: "ocean", label: "Ocean", color: "#00B8D9", isFixed: true },
  { value: "blue", label: "Blue", color: "#0052CC", isDisabled: true },
  { value: "purple", label: "Purple", color: "#5243AA" },
  { value: "red", label: "Red", color: "#FF5630", isFixed: true },
  { value: "orange", label: "Orange", color: "#FF8B00" },
  { value: "yellow", label: "Yellow", color: "#FFC400" },
  { value: "green", label: "Green", color: "#36B37E" },
  { value: "forest", label: "Forest", color: "#00875A" },
  { value: "slate", label: "Slate", color: "#253858" },
  { value: "silver", label: "Silver", color: "#666666" }
];
